### ISSUE TITLE
tab category

### ISSUE THREAD

**Issue by Ulf3000** [Pullusb/greasepencil-addon#1]
can you make this use the same tab category as your other addons "brush fill" and "stroke refine" ??

**Comment by Pullusb** [comment]
Hi, this addon GP addon is a bit special, it is made with the review and feebacks of the grease pencil team with the purpose of entering the native contribs's testing addons of blender and (hopefully) later added as official blender addon.

As such, I don't have final decision about tab name (It has to be normalized to fit Blender standards and UI).

But, I agree with you, taking another tab is no good for the user.
So I think I'll add a way to choose your own tab name in user preferences (if it's ok with the GPteam)
Will do this when I get some free time and update you here.

Thx for your interest.

**Comment by Ulf3000** [comment]
> 
> 

> Thx for your interest.

thanx for making it , all your addons are really great.

i now fixed it myself cause there are no other addons yet with "grease pencil" tab.

**Comment by Pullusb** [comment]
Hi @Ulf3000,
Happy that my codes could be usefull to you :) .
The new version I just pushed include a text field in addon preference to choose category name.

Keep me updated (and reopen the issue) if this fail for you in any ways.
Happy blending
