### ISSUE TITLE
Timeline Scrub has error when trying to Snap

### ISSUE THREAD

**Issue by etufoz** [Pullusb/greasepencil-addon#16]
Hi,

When using the Timeline Scrub in Blender 3.1, all is fine until I try to Snap to keys.  The error happens when "Always Snap" is enabled as well.  "Rolling Mode" works fine.

Here is the error:
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\greasepencil_tools\timeline_scrub.py", line 456, in modal
    context.scene.frame_current = self.new_frame
TypeError: bpy_struct: item.attr = val: Scene.frame_current expected an int type, not numpy.float64

location: <unknown location>:-1
```

The Timeline Overlay also remains on screen with each error.

**Comment by Pullusb** [comment]
Hi, Thanks for the report!
Will look at it asap.
Problem is... This will stay in current Blender version.
So you can either wait for a corrective release / next version, or install the addon from this repo (Once bug is corrected).

Will keep you updated here

**Comment by etufoz** [comment]
Hi Pullusb, I'll likely get the addon as soon as it's updated.  Appreciate your work :)

**Comment by Pullusb** [comment]
Hi, should be fixed.
Thanks again for the thorough report, and your kind words :)

**Comment by etufoz** [comment]
Wow, that was quick!! All fixed up now, thanks :)
