### ISSUE TITLE
Pressing Hotkey "Y" results in error with 4.3 beta

### ISSUE THREAD

**Issue by piotrnikov** [Pullusb/greasepencil-addon#32]
Hello Sam,
Sorry to bother you but I have this error when using Y (to choose a layer):
![Screenshot 2024-11-03 at 10 24 11](https://github.com/user-attachments/assets/0388a4a9-be11-4956-a2b3-02491843224f)
Is it just me?
Thanks!
P.

Blender 4.3 latest Beta
MacOs 15.1

**Comment by Pullusb** [comment]
Ok ! Thanks for the report.
Will fix this quick

**Comment by Pullusb** [comment]
Just a bad addon packaging. Will be fixed in next update
