### ISSUE TITLE
Add shortcut to prevent clearing of the lattice

### ISSUE THREAD

**Issue by Pullusb** [Pullusb/greasepencil-addon#6]
Valid the lattice and keep it.
Maybe using `Shift+Enter` shortcut

**Comment by RossAtElliottAnimaiton** [comment]
Nice, the Shift+Enter function works exactly as it should. I did however manage to tab out of the lattice. This kept the lattice, but it did not create a lattice modifier. I will upload a video showing this.

**Comment by Pullusb** [comment]
Perfect. Closing the task
Don't hesitate to reopen if you find a bug

**Comment by RossAtElliottAnimaiton** [comment]
Okay thanks!
