### ISSUE TITLE
 Box Deform Confirm hot key Numpad Enter not working

### ISSUE THREAD

**Issue by hashman63** [Pullusb/greasepencil-addon#8]
When I want to confirm my actions for Box Deform using Numpad Enter, it does not work. Confirmation can only be done with Enter on the main keyboard. Which is very inconvenient.
Thank you for understanding.

**Comment by Pullusb** [comment]
Hi,
I'll add `numpad_enter` to valid in the next update.
In the meantime, did you know you can also confirm using Spacebar ? Fast reach from left thumb.

**Comment by hashman63** [comment]
Many thanks!

ср, 21 июл. 2021 г. в 19:23, Samuel Bernou ***@***.***>:

**Comment by Pullusb** [comment]
Shortcut added in following commit : https://developer.blender.org/rBA326e03a597cfe32db0ea234807ada69b9971e76b
